In [1]:
import numpy as np 
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\200606040.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 39, in <module>
    from pandas.compat import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "C:\Users\arvin\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\200606040.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "C:\Users\arvin\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\200606040.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\arvin\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\arvin\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\arvin\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\200606040.py", line 2, in <module>
    import pandas as pd
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\arvin\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\arvin\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\arvin\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [2]:
dict1 = {
    "name" : ['harry','rohan','skillf','shubh'],
    "marks" : [92,34,23,44],
    "city" : ['rampur','kolkata','bareilly','antarctica']
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks        city
0   harry     92      rampur
1   rohan     34     kolkata
2  skillf     23    bareilly
3   shubh     44  antarctica

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_false_index.csv',index = False)

In [7]:
df.head(2) #for displaying first 2 rows

    name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

In [8]:
df.tail(1) # for displaying last row

    name  marks        city
3  shubh     44  antarctica

In [9]:
df.tail() # for displaying few last rows

     name  marks        city
0   harry     92      rampur
1   rohan     34     kolkata
2  skillf     23    bareilly
3   shubh     44  antarctica

In [10]:
df.describe() #statistical analysis

          marks
count   4.00000
mean   48.25000
std    30.40148
min    23.00000
25%    31.25000
50%    39.00000
75%    56.00000
max    92.00000

In [11]:
dict2 = {
    "name" : ['Arvind','Minni','Tanu'],
    "std" : ['2nd year','1st year','post graduate'],
    "city" : ['Patiala','Ludhiana','Ludhiana']
}

In [12]:
df2 = pd.DataFrame(dict2)

In [13]:
df2

     name            std      city
0  Arvind       2nd year   Patiala
1   Minni       1st year  Ludhiana
2    Tanu  post graduate  Ludhiana

In [14]:
df2.to_csv('Names.csv',index = False)

In [15]:
Names = pd.read_csv('Names.csv')

In [16]:
Names

     name            std      city
0  Arvind       2nd year   Patiala
1   Minni       1st year  Ludhiana
2    Tanu  post graduate  Ludhiana

In [17]:
Names['std'][0] = '2nd year'

C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\1341130119.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Names['std'][0] = '2nd year'

In [18]:
Names

     name            std      city
0  Arvind       2nd year   Patiala
1   Minni       1st year  Ludhiana
2    Tanu  post graduate  Ludhiana

In [19]:
Names.index = ['first','second','third']

In [20]:
Names

          name            std      city
first   Arvind       2nd year   Patiala
second   Minni       1st year  Ludhiana
third     Tanu  post graduate  Ludhiana

In [21]:
ser = pd.Series(np.random.rand(34))

In [22]:
ser

0     0.774253
1     0.302277
2     0.359122
3     0.529168
4     0.385472
5     0.666921
6     0.428261
7     0.104758
8     0.747549
9     0.335085
10    0.052990
11    0.765840
12    0.600947
13    0.121239
14    0.295262
15    0.329936
16    0.707269
17    0.691614
18    0.238945
19    0.853600
20    0.363976
21    0.390606
22    0.520714
23    0.345766
24    0.093406
25    0.510661
26    0.178716
27    0.675723
28    0.426412
29    0.541160
30    0.807432
31    0.470493
32    0.145070
33    0.111986
dtype: float64

In [23]:
type(ser)

pandas.core.series.Series

In [24]:
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))

In [25]:
type(newdf)

pandas.core.frame.DataFrame

In [26]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.507903    0.499956    0.509253    0.500169    0.500522
std      0.286706    0.299284    0.285845    0.295164    0.292955
min      0.000842    0.000578    0.000416    0.003201    0.000730
25%      0.279224    0.239486    0.275561    0.247543    0.251175
50%      0.522074    0.503203    0.526737    0.463827    0.484637
75%      0.734511    0.757834    0.741804    0.767873    0.748843
max      0.999566    0.997102    0.997242    0.999983    0.997625

In [27]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [28]:
newdf.head()

          0         1         2         3         4
0  0.242415  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3  0.730400  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [29]:
newdf[0][0] = 'harry'

C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\1210831530.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = 'harry'
C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\1210831530.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = 'harry'

In [30]:
newdf.head()

          0         1         2         3         4
0     harry  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3    0.7304  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [31]:
 newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [32]:
 newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [33]:
newdf.to_numpy()

array([['harry', 0.6502345716439002, 0.6574276170254298,
        0.8972339992066533, 0.9320082149045446],
       [0.9077511854638214, 0.808019643913907, 0.2984089014367648,
        0.9176709216003058, 0.5233516297172536],
       [0.8169429866325983, 0.5353611722707379, 0.3554773310039998,
        0.2285700472046981, 0.7081461454224861],
       ...,
       [0.047975838672726145, 0.3862751354728515, 0.2653598947138198,
        0.9544554803572078, 0.02705579725013718],
       [0.379124039997772, 0.936724553931976, 0.08595364108584036,
        0.15455934144768457, 0.8386436199123137],
       [0.9715870939782886, 0.9898004930829413, 0.8851581683944215,
        0.8360433373498657, 0.9554833603259133]], dtype=object)

In [34]:
newdf[0][0] = 0.2

In [35]:
newdf.head()

          0         1         2         3         4
0       0.2  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3    0.7304  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [36]:
newdf.T #transpose

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.2,0.907751,0.816943,0.7304,0.665216,0.836999,0.493172,0.031025,0.704383,0.651631,...,0.632757,0.163001,0.967315,0.480462,0.621177,0.685363,0.719114,0.047976,0.379124,0.971587
1,0.650235,0.80802,0.535361,0.388219,0.878732,0.554772,0.63407,0.986785,0.833727,0.451517,...,0.649269,0.769442,0.390962,0.51237,0.836002,0.757768,0.952701,0.386275,0.936725,0.9898
2,0.657428,0.298409,0.355477,0.330903,0.98029,0.641215,0.292474,0.873456,0.381824,0.701527,...,0.987859,0.314371,0.370441,0.02197,0.964119,0.501195,0.13282,0.26536,0.085954,0.885158
3,0.897234,0.917671,0.22857,0.253489,0.311349,0.532159,0.276153,0.911199,0.839131,0.382998,...,0.678869,0.441889,0.982658,0.023857,0.272837,0.999983,0.503614,0.954455,0.154559,0.836043
4,0.932008,0.523352,0.708146,0.845935,0.40419,0.871612,0.240833,0.223575,0.360542,0.72244,...,0.693024,0.010807,0.929452,0.905401,0.989137,0.908142,0.37786,0.027056,0.838644,0.955483

In [37]:
newdf.head()

          0         1         2         3         4
0       0.2  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3    0.7304  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [38]:
newdf.sort_index(axis = 0 , ascending = False )

            0         1         2         3         4
333  0.971587  0.989800  0.885158  0.836043  0.955483
332  0.379124  0.936725  0.085954  0.154559  0.838644
331  0.047976  0.386275  0.265360  0.954455  0.027056
330  0.719114  0.952701  0.132820  0.503614  0.377860
329  0.685363  0.757768  0.501195  0.999983  0.908142
..        ...       ...       ...       ...       ...
4    0.665216  0.878732  0.980290  0.311349  0.404190
3      0.7304  0.388219  0.330903  0.253489  0.845935
2    0.816943  0.535361  0.355477  0.228570  0.708146
1    0.907751  0.808020  0.298409  0.917671  0.523352
0         0.2  0.650235  0.657428  0.897234  0.932008

[334 rows x 5 columns]

In [39]:
newdf.head()

          0         1         2         3         4
0       0.2  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3    0.7304  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [40]:
newdf2 = newdf

In [41]:
newdf2[0][0] = 9876

In [42]:
newdf2

            0         1         2         3         4
0        9876  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [43]:
newdf2 = newdf.copy()

In [44]:
newdf2[0][0] = 22

C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\3363551159.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 22
C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\3363551159.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 22

In [45]:
newdf

            0         1         2         3         4
0        9876  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [46]:
newdf2 = newdf

In [47]:
newdf2

            0         1         2         3         4
0        9876  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [48]:
newdf2

            0         1         2         3         4
0        9876  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [49]:
newdf

            0         1         2         3         4
0        9876  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [50]:
newdf.head()

          0         1         2         3         4
0      9876  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146
3    0.7304  0.388219  0.330903  0.253489  0.845935
4  0.665216  0.878732  0.980290  0.311349  0.404190

In [51]:
newdf.loc[0,0] = 654

In [52]:
newdf.head(2)

          0         1         2         3         4
0       654  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352

In [53]:
newdf.columns = list('ABCDE')

In [54]:
newdf.head(2)

          A         B         C         D         E
0       654  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352

In [55]:
newdf.loc[0,0] = 22 
newdf.loc[0,'A'] = 1234

In [56]:
newdf

            A         B         C         D         E     0
0        1234  0.650235  0.657428  0.897234  0.932008  22.0
1    0.907751  0.808020  0.298409  0.917671  0.523352   NaN
2    0.816943  0.535361  0.355477  0.228570  0.708146   NaN
3      0.7304  0.388219  0.330903  0.253489  0.845935   NaN
4    0.665216  0.878732  0.980290  0.311349  0.404190   NaN
..        ...       ...       ...       ...       ...   ...
329  0.685363  0.757768  0.501195  0.999983  0.908142   NaN
330  0.719114  0.952701  0.132820  0.503614  0.377860   NaN
331  0.047976  0.386275  0.265360  0.954455  0.027056   NaN
332  0.379124  0.936725  0.085954  0.154559  0.838644   NaN
333  0.971587  0.989800  0.885158  0.836043  0.955483   NaN

[334 rows x 6 columns]

In [57]:
newdf.head

<bound method NDFrame.head of             A         B         C         D         E     0
0        1234  0.650235  0.657428  0.897234  0.932008  22.0
1    0.907751  0.808020  0.298409  0.917671  0.523352   NaN
2    0.816943  0.535361  0.355477  0.228570  0.708146   NaN
3      0.7304  0.388219  0.330903  0.253489  0.845935   NaN
4    0.665216  0.878732  0.980290  0.311349  0.404190   NaN
..        ...       ...       ...       ...       ...   ...
329  0.685363  0.757768  0.501195  0.999983  0.908142   NaN
330  0.719114  0.952701  0.132820  0.503614  0.377860   NaN
331  0.047976  0.386275  0.265360  0.954455  0.027056   NaN
332  0.379124  0.936725  0.085954  0.154559  0.838644   NaN
333  0.971587  0.989800  0.885158  0.836043  0.955483   NaN

[334 rows x 6 columns]>

In [58]:
newdf.head(3)

          A         B         C         D         E     0
0      1234  0.650235  0.657428  0.897234  0.932008  22.0
1  0.907751  0.808020  0.298409  0.917671  0.523352   NaN
2  0.816943  0.535361  0.355477  0.228570  0.708146   NaN

In [59]:
newdf.drop(0,axis = 1) # axis 1 = column and axis = 0 is row

            A         B         C         D         E
0        1234  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [60]:
 newdf.loc[[1,2] , ['C','D']]

          C         D
1  0.298409  0.917671
2  0.355477  0.228570

In [61]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E   0
7    0.031025  0.986785  0.873456  0.911199  0.223575 NaN
10   0.115777  0.760656  0.838134  0.565447  0.125524 NaN
13   0.012367  0.282618  0.085955  0.609977  0.498815 NaN
20   0.057769  0.666808  0.877813  0.765853  0.053461 NaN
26   0.156387  0.946117  0.304277  0.718648  0.526455 NaN
..        ...       ...       ...       ...       ...  ..
312  0.212117  0.763532  0.948841  0.182488  0.996909 NaN
317  0.089515  0.356157  0.734027  0.924218  0.661098 NaN
320  0.198686  0.027486  0.681082  0.774243  0.174696 NaN
325  0.163001  0.769442  0.314371  0.441889  0.010807 NaN
331  0.047976  0.386275  0.265360  0.954455  0.027056 NaN

[93 rows x 6 columns]

In [62]:
newdf.drop(0 , axis = 1 )

            A         B         C         D         E
0        1234  0.650235  0.657428  0.897234  0.932008
1    0.907751  0.808020  0.298409  0.917671  0.523352
2    0.816943  0.535361  0.355477  0.228570  0.708146
3      0.7304  0.388219  0.330903  0.253489  0.845935
4    0.665216  0.878732  0.980290  0.311349  0.404190
..        ...       ...       ...       ...       ...
329  0.685363  0.757768  0.501195  0.999983  0.908142
330  0.719114  0.952701  0.132820  0.503614  0.377860
331  0.047976  0.386275  0.265360  0.954455  0.027056
332  0.379124  0.936725  0.085954  0.154559  0.838644
333  0.971587  0.989800  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [63]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]

            A         B         C         D         E   0
7    0.031025  0.986785  0.873456  0.911199  0.223575 NaN
10   0.115777  0.760656  0.838134  0.565447  0.125524 NaN
20   0.057769  0.666808  0.877813  0.765853  0.053461 NaN
26   0.156387  0.946117  0.304277  0.718648  0.526455 NaN
31    0.01144  0.265488  0.948989  0.513320  0.285211 NaN
..        ...       ...       ...       ...       ...  ..
312  0.212117  0.763532  0.948841  0.182488  0.996909 NaN
317  0.089515  0.356157  0.734027  0.924218  0.661098 NaN
320  0.198686  0.027486  0.681082  0.774243  0.174696 NaN
325  0.163001  0.769442  0.314371  0.441889  0.010807 NaN
331  0.047976  0.386275  0.265360  0.954455  0.027056 NaN

[86 rows x 6 columns]

In [64]:
newdf.head(2)

          A         B         C         D         E     0
0      1234  0.650235  0.657428  0.897234  0.932008  22.0
1  0.907751  0.808020  0.298409  0.917671  0.523352   NaN

In [65]:
newdf.iloc[0,4]

np.float64(0.9320082149045446)

In [66]:
newdf.iloc[ [0,1] , [1,2] ]

          B         C
0  0.650235  0.657428
1  0.808020  0.298409

In [67]:
newdf.head(3)

          A         B         C         D         E     0
0      1234  0.650235  0.657428  0.897234  0.932008  22.0
1  0.907751  0.808020  0.298409  0.917671  0.523352   NaN
2  0.816943  0.535361  0.355477  0.228570  0.708146   NaN

In [68]:
newdf.drop([0],axis = 1 ,inplace= True)

In [69]:
newdf.head(3)

          A         B         C         D         E
0      1234  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146

In [70]:
newdf.reset_index(drop = True,inplace = True)

###

In [72]:
newdf.head(3)

          A         B         C         D         E
0      1234  0.650235  0.657428  0.897234  0.932008
1  0.907751  0.808020  0.298409  0.917671  0.523352
2  0.816943  0.535361  0.355477  0.228570  0.708146

In [73]:
newdf.loc[:,['B']] = None

C:\Users\arvin\AppData\Local\Temp\ipykernel_10476\3577041286.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[:,['B']] = None

In [74]:
newdf

            A     B         C         D         E
0        1234  None  0.657428  0.897234  0.932008
1    0.907751  None  0.298409  0.917671  0.523352
2    0.816943  None  0.355477  0.228570  0.708146
3      0.7304  None  0.330903  0.253489  0.845935
4    0.665216  None  0.980290  0.311349  0.404190
..        ...   ...       ...       ...       ...
329  0.685363  None  0.501195  0.999983  0.908142
330  0.719114  None  0.132820  0.503614  0.377860
331  0.047976  None  0.265360  0.954455  0.027056
332  0.379124  None  0.085954  0.154559  0.838644
333  0.971587  None  0.885158  0.836043  0.955483

[334 rows x 5 columns]

In [7]:
newdf.head(index = False)

NameError: name 'newdf' is not defined

In [76]:
df = pd.DataFrame({"name" : ['Alfred','Batman','Alfred'],
                   "toy" : [np.nan,'Batmobile','Bulllwhip' ] ,
                   "born":[ pd.NaT , pd.Timestamp("1940-04-25"),
                          pd.NaT]})

In [77]:
df.head()

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred  Bulllwhip        NaT

In [78]:
df.dropna(how = 'all',axis = 1)

     name        toy       born
0  Alfred        NaN        NaT
1  Batman  Batmobile 1940-04-25
2  Alfred  Bulllwhip        NaT

In [79]:
df.drop_duplicates(subset = ['name'], keep = False )

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [80]:
df.shape

(3, 3)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     2 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [82]:
df['name'].value_counts(dropna = False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [83]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

In [177]:
book = pd.read_excel('Book1.xlsx',sheet_name ='Sheet2')

In [9]:
book.iloc[0,0] = None

NameError: name 'book' is not defined

In [11]:
book

NameError: name 'book' is not defined

In [195]:
book.to_excel('Book1.xlsx' , sheet_name="Sheet2")

In [193]:
book

      name      place  animal   thing
0        34   ahmdabad    none    axe
1    chirag  chamurchi     cat   cane
2  veronica   victoria    NONE  Vimal