In [3]:
import pandas as pd

In [5]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', None],
    'Age': [25, None, 35, 40, 28],
    'City': ['New York', 'Los Angeles', None, 'Houston', 'Chicago']
}

In [7]:
df = pd.DataFrame(data)

In [16]:
df.fillna(0) #replace with 0

      Name   Age         City
0    Alice  25.0     New York
1      Bob   0.0  Los Angeles
2  Charlie  35.0            0
3    David  40.0      Houston
4        0  28.0      Chicago

In [27]:
df.dropna() #deleting elements with nan

      Name   Age         City
0    Alice  25.0     New York
1      Bob   0.0  Los Angeles
2  Charlie  35.0            0
3    David  40.0      Houston
4        0  28.0      Chicago